name: Scheduler

on:
    push:
        branches:
        - master
    schedule:
        - cron: '*/5 * * * *'

jobs:
    auto_commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3      
                with:
                persist-credentials: false
                fetch-depth: 0

            - name: Change file
                run: |
                    d=`date '+%Y-%m-%dT%H:%M:%SZ'`
                    echo $d > TIME_COMMIT

            - name: Crate a commit
                run: |
                    git config --local user.email "firmnardians@gmail.com"
                    git config --local user.name "firmnardians"
                    git add .
                    git commit -m "Auto Commit"

            - name: Push to Github
                uses: ad-m/github-push-action@v0.6.0
                with:
                directory: "."
                github_token: ${{ secrets.GITHUB_TOKEN }}
