name: Scheduler

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 7,9,11 * * 1,3'

jobs:
    auto_commit:
        runs-on: ubuntu-latest
        steps:
            - name: git init
              run: |
                  git init
            - name: Change file
              run: |
                  d=`date '+%Y-%m-%dT%H:%M:%SZ'`
                  echo $d > TIME_COMMIT
            - name: Crate a commit
              run: |
                  git config --local user.email "firmnardians@gmail.com"
                  git config --local user.name "firmnardians"
                  git add .
                  git commit -m "Test"
            - name: Push to Github
              run: |
                  git remote add origin https://github.com/firmnardians/github.yml.git
                  git push -u origin master
